services:
  fastapi:
    build: .
    volumes:
      - ./qr_codes:/myapp/qr_codes
      - ./:/myapp/
    environment:
      - QR_CODE_DIR=/myapp/qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white
    ports:
      - "8000:8000"  # Exposing FastAPI on port 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Use the correct nginx.conf path
      - ./qr_codes:/var/www/qr_codes  # This assumes qr_codes is the directory where you store images
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - fastapi  # Ensure Nginx starts after FastAPI
    command: ["nginx", "-g", "daemon off;"]
